import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "../utils/trpc";

type HeadCardProps = {
  name: string;
  description: string;
  documentation: string;
};
type ArmCardProps = {
  name: string;
  description: string;
  documentation: string;
};
type TorsoCardProps = {
  name: string;
  description: string;
  documentation: string;
};
type LegCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const Landing: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Dan Brown</title>
        {/* TODO replace metadata */}
        <meta name="description" content="Generated by create-t3-app" />
        {/* TODO Add my own favicon */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center h-screen p-4">
        {/* Make a circle here with my profile picture */}
        <HeadCard
          name="Dan Brown"
          description="Software Engineer and Writer"
          documentation="ljoewjifow"
        />
        {/* arms and torso */}
        <div className="mx-auto flex flex-row justify-between h-screen ">
          {/* left arm */}
          <ArmCard
            name="Left Arm"
            description="The left arm is the main part of the body, and is the main part of the human body."
            documentation="https://en.wikipedia.org/wiki/Left_arm"
          />
          {/* torso  */}
          <TorsoCard
            name="Torso"
            description="The torso is the main part of the body, and is the main part of the human body."
            documentation="https://en.wikipedia.org/wiki/Torso"
          />
          {/* right arm */}
          <ArmCard
            name="Right Arm"
            description="The right arm is the main part of the body, and is the main part of the human body."
            documentation="https://en.wikipedia.org/wiki/Left_arm"
          />
        </div>
        {/* legs */}
        <div className="mx-auto flex flex-row justify-between h-screen hover:h-full">
          {/* left leg */}
          <LegCard
            name="Left Leg"
            description="The left leg is the main part of the body, and is the main part of the human body."
            documentation="https://en.wikipedia.org/wiki/Left_leg"
          />
          {/* right leg */}
          <LegCard
            name="Left Leg"
            description="The left leg is the main part of the body, and is the main part of the human body."
            documentation="https://en.wikipedia.org/wiki/Left_leg"
          />
        </div>
      </main>
    </>
  );
};

const HeadCard = ({ name, description, documentation }: HeadCardProps) => {
  return (
    <div className="flex flex-col items-center justify-center h-screen p-4">
      <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
        <span className="text-violet-900">Dan Brown</span>
      </h1>
      <p className="text-2xl text-gray-700">
        <span className="text-violet-900">Dan Brown</span> is a software
        engineer and a writer.
      </p>
    </div>
  );
};

const ArmCard = ({ name, description, documentation }: ArmCardProps) => {
  return (
    <div className="flex flex-col items-center justify-center h-96 w-48 p-4">
      <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
        <span className="text-violet-900">{name}</span>
      </h1>
    </div>
  );
};

const TorsoCard = ({ name, description, documentation }: TorsoCardProps) => {
  return (
    <section className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{name}</h2>
      <p className="text-sm text-gray-600">{description}</p>
      <a
        className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
        href={documentation}
        target="_blank"
        rel="noreferrer"
      >
        Documentation
      </a>
    </section>
  );
};

const LegCard = ({ name, description, documentation }: LegCardProps) => {
  return (
    <section className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{name}</h2>
      <p className="text-sm text-gray-600">{description}</p>
      <a
        className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
        href={documentation}
        target="_blank"
        rel="noreferrer"
      >
        Documentation
      </a>
    </section>
  );
};

export default Landing;
